spring:
  application:
    name: tp
  datasource:
    url: jdbc:postgresql://localhost:5432/tp
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: validate

management:
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
    logging:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/logs